### ISSUE TITLE
Two packaging issues

### ISSUE THREAD

**Issue by mcepl** [python-rope/pylsp-rope#1]
1. https://pypi.org/project/pylsp-rope/ gives me 404
2. looking at `setup.cfg` I don't see this package depending on `rope` itself. Shouldn't it?

**Comment by lieryan** [comment]
Hi mcepl, yeah, I hadn't uploaded the package to PyPI yet. Give me a couple mins and I'll do so.

> 2. looking at setup.cfg I don't see this package depending on rope itself. Shouldn't it?

Good catch. That should be added.

**Comment by lieryan** [comment]
pylsp-rope 0.1 is now [live on PyPI](https://pypi.org/project/pylsp-rope/). 

🥳🎉
