### ISSUE TITLE
Pip build includes `test` package

### ISSUE THREAD

**Issue by lukasjuhrich** [python-rope/pylsp-rope#10]
The pip package bundles the `test` package, which pollutes the global namespace.
In particular, the AUR package `python-pylsp-rope` occupies `/usr/lib/python3.10/site-packages/test`.

**Comment by lukasjuhrich** [comment]
https://github.com/python-rope/pylsp-rope/blob/431415560779881b57048dc563802705f7556bca/setup.cfg#L23

According to [the setuptools doc](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#configuring-setuptools-using-setup-cfg-files), adding
```
[options.packages.find]
exclude =
    tests*
```
should do the trick.

**Comment by lieryan** [comment]
Hi @lukasjuhrich, thanks for taking the time to report and investigate this issue. I've updated the package on pylsp-rope==0.1.10 on PyPI which should fix this issue. It may take some time for the update to trickle to AUR and other distro repositories.

cc: @bageljrkhanofemus

**Comment by bageljrkhanofemus** [comment]
![image](https://user-images.githubusercontent.com/57874654/186573930-4e8cb137-e720-4999-a169-ae4d69e8bc90.png)
Done.

**Comment by lieryan** [comment]
Thanks @bageljrkhanofemus

**Comment by lukasjuhrich** [comment]
Alright, thanks to both of you for the quick reaction!
