### ISSUE TITLE
Don't make the package >= 3.9 only

### ISSUE THREAD

**Issue by mcepl** [python-rope/pylsp-rope#2]
* pylsp-rope version: 0.1.2
* Text editor/IDE/LSP Client: any
* Python version: 3.6, 3.8
* Operating System: Linux (packaging pylsp-rope for openSUSE/Factory)

### Description

`pylsp_rope/project.py` uses decorator `functools.cache` which was however introduced only in Python 3.9. It is pity to limit this plugin just to Python 3.9, when python-lsp is still 3.6+.

[This patch](https://github.com/python-rope/pylsp-rope/files/7274456/functools-cache.patch.txt) makes the code testable on all supported Python 3 versions.

**Comment by lieryan** [comment]
Fixed!
