### ISSUE TITLE
No code actions available after install

### ISSUE THREAD

**Issue by staticf0x** [python-rope/pylsp-rope#21]
* pylsp-rope version: 0.1.11
* Text editor/IDE/LSP Client: Sublime Text 4, python-lsp-server
* Python version: 3.11.1
* Operating System: Fedora 37

### Description

I installed pylsp-rope via `pip3 install --user pylsp-rope`, but I don't get any code actions. Is any configuration required?

### Details

From pylsp.log:

```
INFO - pylsp.config.config - Loaded pylsp plugin rope_autoimport from <module 'pylsp.plugins.rope_autoimport' from '/home/username/.cache/sublime-text/Package Storage/LSP-pylsp/lib64/python3.11/site-packages/pylsp/plugins/rope_autoimport.py'>
INFO - pylsp.config.config - Loaded pylsp plugin rope_completion from <module 'pylsp.plugins.rope_completion' from '/home/username/.cache/sublime-text/Package Storage/LSP-pylsp/lib64/python3.11/site-packages/pylsp/plugins/rope_completion.py'>
INFO - pylsp.config.config - Loaded pylsp plugin rope_rename from <module 'pylsp.plugins.rope_rename' from '/home/username/.cache/sublime-text/Package Storage/LSP-pylsp/lib64/python3.11/site-packages/pylsp/plugins/rope_rename.py'>
```
But that seems to be the plugins bundled with python-lsp-server already, not the one I just installed, which is located in `~/.local/lib/python3.11/site-packages` and doesn't seem to be discovered by python-lsp-server.

If I go to `~/.cache/sublime-text/Package Storage/LSP-pylsp/lib64/python3.11/site-packages` and do `pip3 install --target=. pylsp-rope` it works fine.

**Comment by lieryan** [comment]
Hi @staticf0x, thanks for writing this report. 

pylsp-rope should be automatically discovered by python-lsp-server as long as you install pylsp-rope to the same virtual environment/python path as python-lsp-server itself. That's not something that's likely to change anytime soon, that's just how the plugin search mechanism used by pylsp works, it expects to be able to import pylsp-rope.

I don't use Sublime, but from your description, it looks like Sublime creates a virtualenv in `~/.cache/sublime-text/Package Storage/LSP-pylsp/`? In which case, the proper way to install pylsp-rope possibly would be something like `~/.cache/sublime-text/Package Storage/LSP-pylsp/bin/pip install pylsp-rope`. 

It is useful for us to document the common configuration and pylsp install locations used by popular editors, it would be very helpful if you can help write the docs for Sublime. The place we currently document this is the Rope Wiki, refer to https://github.com/python-rope/rope/wiki/Rope-in-Vim-or-Neovim for an existing example of editor specific documentation in Rope Wiki.

**Comment by staticf0x** [comment]
Hi @lieryan  thanks for the prompt reply, I will try to play with sublime a bit more and try to write it all down. I just realized that when I was installing python-lsp-server I used `python-lsp-server[all]` which installed the plugins for black, isort, etc... but with pylsp-rope it's and extra package and that might cause issues with the sublime distribution. Or maybe deleting the sublime cache would help, I don't know yet, but I'll try to get back to this!

**Comment by lieryan** [comment]
pylsp-rope is a separate package, but installing `python-lsp-server[all]` would also set up the built-in rope in pylsp (after enabling the relevant feature flags in pylsp configuration).

The builtin support for rope in pylsp supports rename refactor, autocomplete, and autoimport, while pylsp-rope supports other more advanced refactoring operations like extract method, etc. There is no overlap in functionalities between the built-in rope and pylsp-rope, so you can install and enable the builtin and pylsp-rope either individually or together.

**Comment by staticf0x** [comment]
Closing this issue as I finally understood (also thanks to you!) how sublime manages python-lsp-server installation. I switched to a user wide installation (`~/.local/lib`) so it's more intuitive to manage. Now it's easy to get pylsp-rope working. Thank you!
