### ISSUE TITLE
Missing files in test/ in the released tarball

### ISSUE THREAD

**Issue by mcepl** [python-rope/pylsp-rope#25]
* pylsp-rope version: 0.1.13
* Text editor/IDE/LSP Client: #N/A
* Python version: 3.11.* (but doesn’t matter)
* Operating System: openSUSE/Tumbleweed

### Description

When packaging this module for openSUSE/Factory, I hit the problem that all tests fail because they miss `test/conftest.py` file, which truly isn’t included in the release tarball.

For example:

```
[    7s] ____________________ ERROR collecting test/test_commands.py ____________________
[    7s] ImportError while importing test module '/home/abuild/rpmbuild/BUILD/pylsp-rope-0.1.13/test/test_commands.py'.
[    7s] Hint: make sure your test modules/packages have valid Python names.
[    7s] Traceback:
[    7s] /usr/lib64/python3.9/importlib/__init__.py:127: in import_module
[    7s]     return _bootstrap._gcd_import(name[level:], package, level)
[    7s] test/test_commands.py:8: in <module>
[    7s]     from test.conftest import create_document
[    7s] E   ModuleNotFoundError: No module named 'test.conftest'
```

### Details

[Complete build log](https://github.com/python-rope/pylsp-rope/files/14563159/_log.txt)

**Comment by lieryan** [comment]
Hi @mcepl, good to see you around, I've pushed a new version 0.1.15 that should address this missing file. LMK if this is still an issue.
