### ISSUE TITLE
[Question] Need to add "typing_extensions" to dependencies?

### ISSUE THREAD

**Issue by yaegassy** [python-rope/pylsp-rope#6]
* pylsp-rope version: 0.1.5
* Text editor/IDE/LSP Client: coc.nvim
* Python version: 3.10
* Operating System: macOS

### Description

Hi, `typing_extensions` is required for "pylsp-rope" to work, right? (Checking the code of "pylsp-rope", it seems that `typing_extensions` is used)

Normally, `typing_extensions` is not included when `python-lsp-server` is installed.

### DEMO (mp4)

- 1st: `pip install python-lsp-server[all] pylsp-rope`
  - [NG] Not working
- Add: `pip install typing_extensions`
  - [OK] It's working

https://user-images.githubusercontent.com/188642/136782751-77aebb1c-11a1-451e-b1ee-d5663560e6cf.mp4

### Note

If you install `pylsp-mypy`, `typing_extensions` will be installed since `mypy` is present

If you add typing_extensions to your pylsp-rope dependencies, you may need to be careful not to conflict with the pylsp-mypy version.

### Misc

- Use `coc-pylsp` (my pylsp check extension) 
  - <https://github.com/yaegassy/coc-pylsp>

**Comment by lieryan** [comment]
Hi @yaegassy, thank you for using pylsp-rope and thank you for writing up this detailed report.

I've updated and released `pylsp-rope==0.1.6` to require `typing-extensions` as a dependency.
